apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  template:
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 10 }}
          {{- end -}}
          