apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "1"
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 10 }}
          {{- end -}}
        - image:  ghcr.io/knative/helloworld-go:latest
          env:
            - name: TARGET
              value: "Go Sample v1"
          ports:
            - containerPort: 8080