apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-set-service
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/KawinL/test_app_set.git
        revision: main
        directories:
          # here it will read the paths under configs and the subpaths under the config paths
          - path: long_running/configs/*/*
  template:
    metadata:
      namespace: argocd
      # you can use the path strings with / delimiter as variables
      name: "{{path[2]}}-{{path.basename}}"
    spec:
      project: default
      source:
        helm:
          # specify different values file based on directories variables
          valueFiles:
            - "values.yaml"
            - "configs/{{path[2]}}/{{path.basename}}/values.yaml"
        path: long_running
        repoURL: https://github.com/KawinL/test_app_set.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
      destination:
        # specify different destinations
        namespace: default
        server: https://kubernetes.default.svc
